# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Guarani spellchecker"
gn = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Guarani, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
gn = "TRANSLATE: A spellchecker for Guarani, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.gn"

[windows]
system_product_code = "{306F5E0B-246F-4DE1-B255-F4661923570A}_is1"
legacy_product_codes = [
    { value = "A77DF771-2B1C-456D-9B03-80BBB02E41A4", kind = "nsis" },
    { value = "FCAB4F81-E7E3-430D-92C5-80C54F34AFA0", kind = "nsis" }
]

[package.speller]
name = "Guarani"
version = "0.1.1"

[package.grammar]
name = "Guarani"
version = "0.1.0"

[package.tts-text-proc]
name = "Guarani"
version = "0.1.0"

[package.hyphenator]
name = "Guarani"
version = "0.1.0"
